import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

List<TextStyle> fonts = [
  GoogleFonts.aBeeZee(height: 1.2),
  GoogleFonts.peddana(height: 0.8),
  GoogleFonts.secularOne(),
  GoogleFonts.josefinSans(),
  GoogleFonts.dancingScript(),
  GoogleFonts.architectsDaughter(),
  GoogleFonts.teko(),
  GoogleFonts.indieFlower(),
  GoogleFonts.amaticSc(),
  GoogleFonts.caveat(),
  GoogleFonts.courgette(),
  GoogleFonts.satisfy(),
  GoogleFonts.pressStart2p(height: 1.5),
  GoogleFonts.concertOne(),
  GoogleFonts.monoton(),
  GoogleFonts.markaziText(),
  GoogleFonts.elMessiri(),
  GoogleFonts.marckScript(),
  GoogleFonts.juliusSansOne(),
  GoogleFonts.frederickaTheGreat(),
  GoogleFonts.bungeeInline(),
  GoogleFonts.nanumBrushScript(),
  GoogleFonts.wallpoet(),
  GoogleFonts.megrim(),
  GoogleFonts.fasterOne(),
  GoogleFonts.oregano(),
  GoogleFonts.cormorantUpright(),
  GoogleFonts.katibeh(),
  GoogleFonts.hiMelody(),
  GoogleFonts.mogra(),
  GoogleFonts.overlockSc(),
];
